version: '3.1'

services:
  app:
    image: pedro6571/fatec-tg-api-donations-points:latest
    container_name: app
    environment:
      - PORT=8080
      - PROFILE=dev
    restart: always
    ports:
      - 8080:8080
