version: '3.1'

services:
  db:
    image: mysql:8.0.31
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_donations
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes: 
      - mysql-data:/var/lib/mysql

  app:
    image: pedro6571/fatec-tg-api-donations-points:latest
    container_name: app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=jdbc:mysql://mysql:3306/db_donations
      - DATABASE_USER=app
      - DATABASE_PASSWORD=app
      - PORT=8080
      - PROFILE=prd
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql-data:
