name: Deploy in AWS EB

on: workflow_call

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.1
        with:
          name: app
          path: ./target

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          region: us-east-1
          application_name: api-donations
          environment_name: Apidonations-env
          version_label: api-donations-${{ github.sha }}
          deployment_package: ./target/donations-0.0.1-SNAPSHOT.jar
          existing_bucket_name: api-donations-s3
          wait_for_deployment: true
