name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      
      - name: Build with Maven
        run: mvn -B package --file pom.xml
    
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: app
          path: ./target/donations-0.0.1-SNAPSHOT.jar

  docker:
    needs: build
    uses: ./.github/workflows/docker.yml
    secrets: inherit

  deploy-infra:
    needs: build
    uses: ./.github/workflows/terraform.yml
    secrets: inherit

  deploy:
    needs: deploy-infra
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
